site_name: Rosetta
docs_dir: rosetta
repo_url: https://github.com/HYP3R00T/Rosetta
repo_name: HYP3R00T/Rosetta
theme:
  icon:
    logo: octicons/terminal-24
    menu: material/dots-grid
    search: octicons/search-24
  name: "material"
  palette:
    primary: custom
    accent: custom
    scheme: dark
  font:
    text: Inter
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - search.share
plugins:
  - search
  - roamlinks
  - callouts
  - termynal:
      title: shell
      buttons: windows
      prompt_literal_start:
        - ">"
  - tags
markdown_extensions:
  - footnotes
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HYP3R00T
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajesh-kumar-das/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/HYP3R00T
  status:
    new: Recently added
extra_css:
  - Extras/stylesheets/extra.css
copyright: Copyright &copy; 2024 hyperoot.dev
